config/routes.rb
Rails.application.routes.draw do
  get 'items/new'
  get 'items/show'

  resources :items
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item 
    include ActiveModel::Model
    attr_accessor :identification, :name, :email, :mobile
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
  
    require 'aws-sdk-dynamodb'
    client = Aws::DynamoDB::Client.new(endpoint: 'http://localhost:8000')

    item = {
      'identification' => @item.identification,
      'sk' => "METADATA2", 
      'Name' => @item.name,
      'email' => @item.email,
      'mobile' => @item.mobile
    }

    client.put_item({
      table_name: 'ingreso',
      item: item
    })
   
  rescue Aws::DynamoDB::Errors::ServiceError => e
    puts "Error al guardar en DynamoDB: #{e.message}"
  end

  def show
    require 'aws-sdk-dynamodb'
    client = Aws::DynamoDB::Client.new(endpoint: 'http://localhost:8000')
    
    response = client.get_item({
      table_name: 'ingreso',
      key: {
        'identification' => params[:id].to_s,
        'sk' => 'METADATA2'

      }
    })
    
    if response.item
      @item = response.item
    else
      @item = nil
    end
  end
  
  private

  def item_params
    params.require(:item).permit(:identification, :name, :email, :mobile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>
<h1>Items</h1>
<ul>
  <% @items.each do |item| %>
    <li>
      <%= item.name %> - <%= item.description %>
    </li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_with(model: @item, url: items_path) do |form| %>
  <br>
  <%= form.label :identification %>
  <%= form.text_field :identification %>
  <br>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <br>
  <%= form.label :mobile %>
  <%= form.text_field :mobile %>
  <br>
  <%= form.submit 'Create Item' %>
<% end %>
<%= stylesheet_link_tag 'styles.css', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/items/show.html.erb
<div class="container">
<h1>Detalles del Usuario</h1>
<% if @item %>
<br>
<div class="mt-4">
  <p><strong>identification:</strong> <%= @item['identification'] %></p>
  <p><strong>Name:</strong> <%= @item['name'] %></p>
  <p><strong>email:</strong> <%= @item['email'] %></p>
  <p><strong>Mobile:</strong> <%= @item['mobile'] %></p>
  </div>
  <%= link_to 'Back to New', new_item_path, class: 'btn btn-secondary' %>

    <% else %>
      <p>Usuario no encontrado</p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formulario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>